test1: solve.zig
	zig build-exe solve.zig
	./solve test.txt

run1: solve.zig
	zig build-exe solve.zig
	./solve input.txt

test2: solve2.zig
	zig build-exe solve2.zig
	./solve2 test.txt

run2: solve2.zig
	zig build-exe solve2.zig
	./solve2 input.txt

clean:
	rm solve solve2
